---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content/open-positions
  label: Open positions
  create: all
  match: "**/*"
- type: directory
  path: content/employees
  label: Employees
  create: all
  match: "**/*"
- type: directory
  path: content/posts
  label: Posts
  create: all
  match: "**/*"
- type: directory
  path: content/case
  label: Case
  create: all
  match: "**/*"
upload_dir: content/media/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: gatsby build
  publish_command: gatsby build
  preview_output_directory: public
  output_directory: public
  instant_preview_command: gatsby develop -H 0.0.0.0 -p 8080
